ui:
  default_width: 450
inputs_def:
  - handle: videoAssets
    description: Output
    json_schema:
      type: array
    nullable: false
  - handle: outputDir
    json_schema:
      type: string
      ui:widget: dir
    nullable: false
  - handle: config
    json_schema:
      type: object
      additionalProperties: false
      properties:
        size:
          enum:
            - 1280x720
            - 720x720
            - 720x1280
          ui:options:
            labels:
              - 1280x720（16:9 - 720p）
              - 720x720（1:1 - 720p）
              - 720x1280（9:16 - 720p）
        format:
          enum:
            - mp4
          ui:options:
            labels:
              - mp4
    value:
      size: 1280x720
      format: mp4
    nullable: true
  - handle: audioAssets
    description: Output
    json_schema:
      type: array
      items:
        type: object
        additionalProperties: false
    nullable: true
  - handle: subtitleAssets
    json_schema:
      type: array
    nullable: true
outputs_def:
  - handle: mergedVideoAsset
    description: Output
    json_schema:
      type: object
      additionalProperties: false
      properties:
        filePath:
          type: string
        duration:
          type: number
        resolution:
          type: string
        fileSize:
          type: number
executor:
  name: nodejs
  options:
    entry: main.ts
    spawn: false
title: Merge Sources
icon: ":skill-icons:typescript:"
